### ISSUE TITLE
세로로 긴 모니터 대응

### ISSUE THREAD

**Issue by dhdbstjr98** [JaehyeokSong0/ProjectSocket#7]
세로로 긴 모니터의 경우 화면이 찌그러집니다.
가로 사이즈 대비 세로 사이즈 비율이 일정 수준을 넘어가지 않도록 하는 것이 좋을 것 같습니다.

![image](https://user-images.githubusercontent.com/42272855/133877873-4545ed01-112b-40d5-bcce-382bded0974d.png)

![image](https://user-images.githubusercontent.com/42272855/133877876-287a0f67-880b-41b8-a177-2bb3e6d2638b.png)

**Comment by JaehyeokSong0** [comment]
[PR #8](https://github.com/JaehyeokSong0/IDT-game/pull/8)을 통해 해결되었습니다.
도움 주신 @dhdbstjr98 님 감사드립니다!!
